platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'

pod 'react-native-webview', :path => '../node_modules/react-native-webview'

target 'VoiceRecorder' do
  # Pods for VoiceRecorder
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
#   pod 'React-RCTPushNotification', :path => '../node_modules/react-native/Libraries/PushNotificationIOS'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

#   pod 'react-native-camera', :path => '../node_modules/react-native-camera'
#   pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'
#   pod 'SwiftyJSON', '5.0'      
#   pod 'Charts', '3.3.0' 

  pod 'RNAudio', :path => '../node_modules/react-native-audio'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'react-native-html-to-pdf', :path => '../node_modules/react-native-html-to-pdf'

  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'

  target 'VoiceRecorderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

swift4 = ['Charts']

 post_install do |installer|
   installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
       if swift4.include?(target.name)
         config.build_settings['SWIFT_VERSION'] = '4.2'
       end
     end
   end
 end

target 'VoiceRecorder-tvOS' do
  # Pods for VoiceRecorder-tvOS

  target 'VoiceRecorder-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
